apriltag_ros_node:
  ros__parameters:
    tag_family: "tag36h11"

    image_topic: "/camera/image_raw"
    camera_info_topic: "/camera/camera_info"

    detection_rate: 10.0

    publish_tf: true
    tf_prefix: "apriltag_"

    tag_ids: []

    visualize: true
