moveit_simple_controller_manager:
  ros__parameters:
    controller_names:
      - arm_controller

    arm_controller:
      type: FollowJointTrajectory
      joints:
        - arm_joint_1
        - arm_joint_2
        - arm_joint_3
        - arm_joint_4
